 <?php include(TEMPLATE_PATH . 'admin/main.phtml'); ?>

<main class="content">
    <div class="content-header ui-content-header">
        <div class="container">
            <h1 class="content-heading">充值码<?php if ($_ENV['enable_donate']) { ?>与捐赠<?php } ?>管理</h1>
        </div>
    </div>
    <div class="container">
        <div class="col-lg-12 col-md-12">
            <section class="content-inner margin-top-no">

                <div class="card">
                    <div class="card-main">
                        <div class="card-inner">
                            <p>系统中金额流转记录。</p>
                            <p>显示表项:
                                <?php include(TEMPLATE_PATH . 'table/checkbox.phtml'); ?>
                            </p>
                        </div>
                    </div>
                </div>

                <div class="table-responsive">
                    <?php include(TEMPLATE_PATH . 'table/table.phtml'); ?>
                </div>

                <div class="fbtn-container">
                    <div class="fbtn-inner">
                        <a class="fbtn fbtn-lg fbtn-brand-accent waves-attach waves-circle waves-light" href="/admin/code/create">+</a>

                    </div>
                </div>

                <div class="fbtn-container">
                    <div class="fbtn-inner">
                        <a class="fbtn fbtn-lg fbtn-brand-accent waves-attach waves-circle waves-light" data-toggle="dropdown"><span class="fbtn-ori icon">add</span><span class="fbtn-sub icon">close</span></a>
                        <div class="fbtn-dropup">
                            <a class="fbtn fbtn-brand waves-attach waves-circle waves-light" href="/admin/code/create"><span class="fbtn-text fbtn-text-left">充值码</span><span class="icon">code</span></a>
<?php if ($_ENV['enable_donate']) { ?>
                            <a class="fbtn fbtn-green waves-attach waves-circle waves-light" href="/admin/donate/create"><span class="fbtn-text fbtn-text-left">捐赠和支出</span><span class="icon">attach_money</span></a>
<?php } ?>
                        </div>
                    </div>
                </div>

            </section>
        </div>
    </div>

</main>

<?php include(TEMPLATE_PATH . 'admin/footer.phtml'); ?>

<script>
<?php include(TEMPLATE_PATH . 'table/js_1.phtml'); ?>

$(document).ready(function(){
    <?php include(TEMPLATE_PATH . 'table/js_2.phtml'); ?>
});
</script>
