<?php include(TEMPLATE_PATH . 'admin/main.phtml'); ?>

    <main class="content">

        <div class="content-header ui-content-header">
            <div class="container">
                <h1 class="content-heading">节点被封IP</h1>
            </div>
        </div>

        <div class="container">
            <div class="col-lg-12 col-sm-12">
                <section class="content-inner margin-top-no">

                    <div class="card">
                        <div class="card-main">
                            <div class="card-inner">
                                <p>这里是最近的节点上捕捉到的进行非法行为的IP。</p>
                                <p>显示表项:
                                    <?php include(TEMPLATE_PATH . 'table/checkbox.phtml'); ?>
                                </p>
                            </div>
                        </div>
                    </div>

                    <div class="card">
                        <div class="card-main">
                            <div class="card-inner">
                                <div class="form-group form-group-label">
                                    <label class="floating-label" for="ip">要解封的IP</label>
                                    <input class="form-control" id="ip" type="text">
                                </div>
                            </div>
                            <div class="card-action">
                                <div class="card-action-btn pull-left">
                                    <a class="btn btn-flat waves-attach" id="unblock" ><span class="icon">check</span>&nbsp;解封</a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="table-responsive">
                        <?php include(TEMPLATE_PATH . 'table/table.phtml'); ?>
                    </div>

<?php include(TEMPLATE_PATH . 'dialog.phtml'); ?>

                </section>
            </div>
        </div>

    </main>

<?php include(TEMPLATE_PATH . 'admin/footer.phtml'); ?>

<script>
<?php include(TEMPLATE_PATH . 'table/js_1.phtml'); ?>

$("#unblock").click(function () {
    $.ajax({
        type: "POST",
        url: "/admin/unblock",
        dataType: "json",
        data: {
            ip: $("#ip").val()
        },
        success: function (data) {
            if (data.ret) {
                $("#result").modal();
                $("#msg").html(data.msg);
                window.setTimeout("location.href=window.location.href", <?= $_ENV['jump_delay']; ?>);
            } else {
                $("#result").modal();
                $("#msg").html(data.msg);
            }
              // window.location.reload();
        },
        error: function (jqXHR) {
            alert("发生错误：" + jqXHR.status);
        }
    })
});

$(document).ready(function(){
     <?php include(TEMPLATE_PATH . 'table/js_2.phtml'); ?>
});
</script>
