<?php include(TEMPLATE_PATH . 'user/main.phtml'); ?>

    <main class="content">

        <div class="content-header ui-content-header">
            <div class="container">
                <h1 class="content-heading">充值</h1>
            </div>
        </div>

        <div class="container">
            <section class="content-inner margin-top-no">
                <div class="row">

                    <div class="col-lg-12 col-md-12">
                        <div class="card margin-bottom-no">
                            <div class="card-main">
                                <div class="card-inner">
                                    <div class="card-inner">
                                        <p class="card-heading">充值码</p>
                                        <p>当前余额：<?= $user->money; ?> 元</p>
                                        <div class="form-group form-group-label">
                                            <label class="floating-label" for="code">充值码</label>
                                            <input class="form-control" id="code" type="text">
                                        </div>
                                    </div>
                                    <div class="card-action">
                                        <div class="card-action-btn pull-left">
                                            <button class="btn btn-flat waves-attach" id="code-update" ><span class="icon">check</span>&nbsp;充值</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

<?php if ($payment_html != '') { ?>
                    <div class="col-lg-12 col-md-12">
                        <div class="card margin-bottom-no">
                            <div class="card-main">
                                <div class="card-inner">
                                    <div class="card-inner">
                                        <?= $payment_html ?>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
<?php } ?>

                    <div class="col-lg-12 col-md-12">
                        <div class="card margin-bottom-no">
                            <div class="card-main">
                                <div class="card-inner">
                                    <div class="card-inner">
                                        <div class="card-table">
                                            <div class="table-responsive">
                                                <?= $codes->render() ?>
                                                <table class="table table-hover">
                                                    <tr>
                                                        <th>ID</th>
                                                        <th>代码</th>
                                                        <th>类型</th>
                                                        <th>操作</th>
                                                        <th>使用时间</th>

                                                    </tr>
<?php
foreach ($codes as $code) {
    if ($code->type != -2) {
?>
                                                            <tr>
                                                                <td>#<?= $code->id; ?></td>
                                                                <td><?= $code->code; ?></td>
<?php   switch ($code->type) { case -1: ?>
                                                                <td>金额充值</td>
<?php       break; case 10001: ?>
                                                                <td>流量充值</td>
<?php       break; case 10002: ?>
                                                                <td>用户续期</td>
<?php       break; } ?>

<?php   if ($code->type >= 1 && $code->type <= 10000) { ?>
                                                                <td>等级续期 - 等级<?= $code->type; ?></td>
<?php   } ?>

<?php   if ($code->type == -1) { ?>
                                                                <td>充值 <?= $code->number; ?> 元</td>
<?php   } ?>

<?php   if ($code->type == 10001) { ?>
                                                                <td>充值 <?= $code->number; ?> GB 流量</td>
<?php   } ?>

<?php   if ($code->type == 10002) { ?>
                                                                <td>延长账户有效期 <?= $code->number; ?> 天</td>
<?php   } ?>

<?php   if ($code->type >= 1 && $code->type <= 10000) { ?>
                                                                <td>延长等级有效期 <?= $code->number; ?> 天</td>
<?php   } ?>
                                                                <td><?= $code->usedatetime; ?></td>
                                                            </tr>
<?php 
    }
}
?>
                                                </table>
                                                <?= $codes->render(); ?>
                                            </div>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>

<?php include(TEMPLATE_PATH . 'dialog.phtml'); ?>
                </div>
            </section>
        </div>
    </main>

<?php include(TEMPLATE_PATH . 'user/footer.phtml'); ?>


<script>
    $(document).ready(function () {
        $("#code-update").click(function () {
            $.ajax({
                type: "POST",
                url: "code",
                dataType: "json",
                data: {
                    code: $("#code").val()
                },
                success: function (data) {
                    if (data.ret) {
                        $("#result").modal();
                        $("#msg").html(data.msg);
                        window.setTimeout("location.href=window.location.href", <?= $_ENV['jump_delay']; ?>);
                    } else {
                        $("#result").modal();
                        $("#msg").html(data.msg);
                        window.setTimeout("location.href=window.location.href", <?= $_ENV['jump_delay']; ?>);
                    }
                },
                error: function (jqXHR) {
                    $("#result").modal();
                    $("#msg").html("发生错误：" + jqXHR.status);
                }
            })
        })


    timestamp = {time()};


    function f(){
        $.ajax({
            type: "GET",
            url: "code_check",
            dataType: "json",
            data: {
                time: timestamp
            },
            success: function (data) {
                if (data.ret) {
                    clearTimeout(tid);
                    $("#result").modal();
                    $("#msg").html("充值成功！");
                    window.setTimeout("location.href=window.location.href", <?= $_ENV['jump_delay']; ?>);
                }
            }
        });
        tid = setTimeout(f, 1000); //循环调用触发setTimeout
    }
    setTimeout(f, 1000);
})
</script>
