<?php include('user/main.phtml'); ?>

    <main class="content">

        <div class="content-header ui-content-header">
            <div class="container">
                <h1 class="content-heading">虚空之地</h1>
            </div>
        </div>

        <div class="container">
            <section class="content-inner margin-top-no">
                <div class="ui-card-wrap">
                    <div class="col-lg-12 col-md-12">
                        <section class="content-inner margin-top-no">
                            <div class="card">
                                <div class="card-main">
                                    <div class="card-inner">
                                        <p>您由于某些原因而被管理员禁用了账户，请联系管理员。</p>
                                    </div>
                                </div>
                            </div>
                        </section>
                    </div>
                </div>
            </section>
        </div>

    </main>

<?php include('user/footer.phtml'); ?>
