<?php
use App\Utils\URL;

include(TEMPLATE_PATH . 'user/header_info.phtml');

$SSR_connectivity = $ssr_prefer = URL::SSRCanConnect($user, $mu);
$SS_connectivity = URL::SSCanConnect($user, $mu);
?>

    <main class="content">

        <div class="content-header ui-content-header">
            <div class="container">
                <h1 class="content-heading">节点信息</h1>
            </div>
        </div>

        <div class="container">
            <section class="content-inner margin-top-no">
                <div class="ui-card-wrap">
                    <div class="row">

                        <div class="col-lg-12 col-sm-12">
                            <div class="card">
                                <div class="card-main">
                                    <div class="card-inner margin-bottom-no">
                                        <p class="card-heading">注意！</p>
                                        <p>配置文件以及二维码请勿泄露！</p>
                                    </div>

                                </div>
                            </div>
                        </div>


                        <div class="col-lg-12 col-sm-12">
                            <div class="card">
                                <div class="card-main">
                                    <div class="card-inner margin-bottom-no">
                                        <p class="card-heading">配置信息</p>
                                        <div class="tab-content">

                                            <nav class="tab-nav margin-top-no">
                                                <ul class="nav nav-list">
                                                    <li <?php if ($ssr_prefer) { ?>class="active"<?php } ?>>
                                                        <a class="waves-attach" data-toggle="tab" href="#ssr_info"><i class="icon icon-lg">airplanemode_active</i>&nbsp;ShadowsocksR</a>
                                                    </li>
                                                    <li <?php if (!$ssr_prefer) { ?>class="active"<?php } ?>>
                                                        <a class="waves-attach" data-toggle="tab" href="#ss_info"><i class="icon icon-lg">flight_takeoff</i>&nbsp;Shadowsocks</a>
                                                    </li>
                                                </ul>
                                            </nav>

                                            <div class="tab-pane fade <?php if ($ssr_prefer) { ?>active in<?php } ?>" id="ssr_info">
<?php if ($SSR_connectivity) {
    $ssr_item = URL::getItem($user, $node, $mu, $relay_rule_id, 0);
?>
                                                    <p>
                                                        服务器地址：<?= $ssr_item['address']; ?><br>
                                                        服务器端口：<?= $ssr_item['port']; ?><br>
                                                        加密方式：<?= $ssr_item['method']; ?><br>
                                                        密码：<?= $ssr_item['passwd']; ?><br>
                                                        协议：<?= $ssr_item['protocol']; ?><br>
                                                        协议参数：<?= $ssr_item['protocol_param']; ?><br>
                                                        混淆：<?= $ssr_item['obfs']; ?><br>
                                                        混淆参数：<?= $ssr_item['obfs_param']; ?><br>
                                                    </p>
<?php } else { ?>
                                                    <p>您好，您目前的 加密方式，混淆，或者协议设置在 ShadowsocksR 客户端下无法连接。请您选用 Shadowsocks 客户端来连接，或者到 资料编辑 页面修改后再来查看此处。</p>
                                                    <p>同时, ShadowsocksR 公共端口的连接不受您设置的影响,您可以在此使用相应的客户端进行连接~</p>
<?php } ?>
                                            </div>

                                            <div class="tab-pane fade <?php if (!$ssr_prefer) { ?>active in<?php } ?>" id="ss_info">
<?php
if ($SSR_connectivity) {
    $ss_item = URL::getItem($user, $node, $mu, $relay_rule_id, 1);
?>
                                                    <p>
                                                        服务器地址：<?= $ss_item['address']; ?><br>
                                                        服务器端口：<?= $ss_item['port']; ?><br>
                                                        加密方式：<?= $ss_item['method']; ?><br>
                                                        密码：<?= $ss_item['passwd']; ?><br>
                                                        混淆：<?= $ss_item['obfs']; ?><br>
                                                        混淆参数：<?= $ss_item['obfs_param']; ?><br>
                                                    </p>
<?php } else { ?>
                                                    <p>您好，您目前的 加密方式，混淆，或者协议设置在 Shadowsocks 客户端下无法连接。请您选用 ShadowsocksR 客户端来连接，或者到 资料编辑 页面修改后再来查看此处。</p>
<?php } ?>
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>



                        <div class="col-lg-12 col-sm-12">
                            <div class="card">
                                <div class="card-main">
                                    <div class="card-inner margin-bottom-no">
                                        <p class="card-heading">客户端下载</p>


                                        <nav class="tab-nav margin-top-no">
                                            <ul class="nav nav-list">
                                                <li <?php if ($ssr_prefer) { ?>class="active"<?php } ?>>
                                                    <a class="waves-attach" data-toggle="tab" href="#ssr_download"><i class="icon icon-lg">airplanemode_active</i>&nbsp;ShadowsocksR</a>
                                                </li>
                                                <li <?php if (!$ssr_prefer) { ?>class="active"<?php } ?>>
                                                    <a class="waves-attach" data-toggle="tab" href="#ss_download"><i class="icon icon-lg">flight_takeoff</i>&nbsp;Shadowsocks</a>
                                                </li>
                                            </ul>
                                        </nav>
                                        <div class="tab-pane fade <?php if ($ssr_prefer) { ?>active in<?php } ?>" id="ssr_download">
<?php if ($SSR_connectivity) { ?>
                                                <p><i class="icon icon-lg">desktop_windows</i>&nbsp;<a href="/ssr-download/ssr-win.7z">Windows</a></p>
                                                <p><i class="icon icon-lg">laptop_mac</i>&nbsp;<a href="/ssr-download/ssr-mac.dmg">Mac OS X</a></p>
                                                <p><i class="icon icon-lg">laptop_windows</i>&nbsp;<a href="https://github.com/breakwa11/shadowsocks-rss/wiki/Python-client">Linux</a></p>
                                                <p><i class="icon icon-lg">android</i>&nbsp;<a href="/ssr-download/ssr-android.apk">Android</a></p>
                                                <p><i class="icon icon-lg">phone_iphone</i>&nbsp;<a href="https://itunes.apple.com/us/app/shadowrocket/id932747118">iOS</a></p>
<?php } else { ?>
                                                <p>您好，您目前的 加密方式，混淆，或者协议设置在 ShadowsocksR 客户端下无法连接。请您选用 Shadowsocks 客户端来连接，或者到 资料编辑 页面修改后再来查看此处。</p>
<?php } ?>
                                        </div>
                                        <div class="tab-pane fade <?php if (!$ssr_prefer) { ?>active in<?php } ?>" id="ss_download">
<?php if ($SSR_connectivity) { ?>
                                                <p><i class="icon icon-lg">desktop_windows</i>&nbsp;<a href="/ssr-download/ss-win.7z">Windows</a></p>
                                                <p><i class="icon icon-lg">laptop_mac</i>&nbsp;<a href="/ssr-download/ss-mac.zip">Mac OS X</a></p>
                                                <p><i class="icon icon-lg">laptop_windows</i>&nbsp;<a href="https://shadowsocks.org/en/download/clients.html">Linux</a></p>
                                                <p><i class="icon icon-lg">android</i>&nbsp;<a href="/ssr-download/ss-android.apk">Android</a></p>
                                                <p><i class="icon icon-lg">android</i>&nbsp;<a href="/ssr-download/ss-android-obfs.apk">Android Obfs插件</a></p>
                                                <p><i class="icon icon-lg">phone_iphone</i>&nbsp;<a href="https://itunes.apple.com/us/app/shadowrocket/id932747118">iOS</a></p>
<?php } else { ?>
                                                <p>您好，您目前的 加密方式，混淆，或者协议设置在 Shadowsocks 客户端下无法连接。请您选用 ShadowsocksR 客户端来连接，或者到 资料编辑 页面修改后再来查看此处。</p>
<?php } ?>
                                        </div>

                                    </div>

                                </div>
                            </div>
                        </div>

                        <div class="col-lg-12 col-sm-12">
                            <div class="card">
                                <div class="card-main">
                                    <div class="card-inner margin-bottom-no">
                                        <p class="card-heading">配置Json</p>

                                        <nav class="tab-nav margin-top-no">
                                            <ul class="nav nav-list">
                                                <li <?php if ($ssr_prefer) { ?>class="active"<?php } ?>>
                                                    <a class="waves-attach" data-toggle="tab" href="#ssr_json"><i class="icon icon-lg">airplanemode_active</i>&nbsp;ShadowsocksR</a>
                                                </li>
                                                <li <?php if (!$ssr_prefer) { ?>class="active"<?php } ?>>
                                                    <a class="waves-attach" data-toggle="tab" href="#ss_json"><i class="icon icon-lg">flight_takeoff</i>&nbsp;Shadowsocks</a>
                                                </li>
                                            </ul>
                                        </nav>
                                        <div class="tab-pane fade <?php if ($ssr_prefer) { ?>active in<?php } ?>" id="ssr_json">
<?php if ($SSR_connectivity) { ?>
                                                <textarea class="form-control" rows="6">
{
    "server": "<?= $ssr_item['address']; ?>",
    "local_address": "127.0.0.1",
    "local_port": 1080,
    "timeout": 300,
    "workers": 1,
    "server_port": <?= $ssr_item['port']; ?>,
    "password": "<?= $ssr_item['passwd']; ?>",
    "method": "<?= $ssr_item['method']; ?>",
    "obfs": "<?= $ssr_item['obfs']; ?>",
    "obfs_param": "<?= $ssr_item['obfs_param']; ?>",
    "protocol": "<?= $ssr_item['protocol']; ?>",
    "protocol_param": "<?= $ssr_item['protocol_param']; ?>"
}
                                                </textarea>
<?php } else { ?>
                                                <p>您好，您目前的 加密方式，混淆，或者协议设置在 ShadowsocksR 客户端下无法连接。请您选用 Shadowsocks 客户端来连接，或者到 资料编辑 页面修改后再来查看此处。</p>
<?php } ?>
                                        </div>
                                        <div class="tab-pane fade <?php if (!$ssr_prefer) { ?>active in<?php } ?> " id="ss_json">
<?php if ($SSR_connectivity) { ?>
                                            <textarea class="form-control" rows="6">
{
        "server": "<?= $ss_item['address']; ?>",
        "local_address": "127.0.0.1",
        "local_port": 1080,
        "timeout": 300,
        "workers": 1,
        "server_port": <?= $ss_item['port']; ?>,
        "password": "<?= $ss_item['passwd']; ?>",
        "method": "<?= $ss_item['method']; ?>",
        "plugin": "<?= URL::getJsonObfs($ss_item); ?>"
}
                                            </textarea>
<?php } else { ?>
                                                <p>您好，您目前的 加密方式，混淆，或者协议设置在 Shadowsocks 客户端下无法连接。请您选用 ShadowsocksR 客户端来连接，或者到 资料编辑 页面修改后再来查看此处。</p>
<?php } ?>
                                        </div>

                                    </div>

                                </div>
                            </div>
                        </div>

                        <div class="col-lg-12 col-sm-12">
                            <div class="card">
                                <div class="card-main">
                                    <div class="card-inner margin-bottom-no">
                                        <p class="card-heading">配置链接</p>

                                        <nav class="tab-nav margin-top-no">
                                            <ul class="nav nav-list">
                                                <li <?php if ($ssr_prefer) { ?>class="active"<?php } ?>>
                                                    <a class="waves-attach" data-toggle="tab" href="#ssr_url"><i class="icon icon-lg">airplanemode_active</i>&nbsp;ShadowsocksR</a>
                                                </li>
                                                <li <?php if (!$ssr_prefer) { ?>class="active"<?php } ?>>
                                                    <a class="waves-attach" data-toggle="tab" href="#ss_url"><i class="icon icon-lg">flight_takeoff</i>&nbsp;Shadowsocks</a>
                                                </li>
                                            </ul>
                                        </nav>
                                        <div class="tab-pane fade <?php if ($ssr_prefer) { ?>active in<?php } ?>" id="ssr_url">
<?php if ($SSR_connectivity) { ?>
                                                <p><a href="<?php URL::getItemUrl($ssr_item, 0); ?>"/>Android 手机上用默认浏览器打开点我就可以直接添加了(给 ShadowsocksR APP)</a></p>
                                                <p><a href="<?php URL::getItemUrl($ssr_item, 0); ?>"/>iOS 上用 Safari 打开点我就可以直接添加了(给 Shadowrocket)</a></p>
<?php } else { ?>
                                                <p>您好，您目前的 加密方式，混淆，或者协议设置在 ShadowsocksR 客户端下无法连接。请您选用 Shadowsocks 客户端来连接，或者到 资料编辑 页面修改后再来查看此处。</p>
<?php } ?>
                                        </div>
                                        <div class="tab-pane fade <?php if (!$ssr_prefer) { ?>active in<?php } ?>" id="ss_url">
<?php if ($SSR_connectivity) { ?>
                                                <p><a href="<?php URL::getItemUrl($ss_item, 1); ?>"/>Android 手机上用默认浏览器打开点我就可以直接添加了(给 Shadowsocks)</a></p>
                                                <p><a href="<?php URL::getItemUrl($ss_item, 1); ?>"/>iOS 上用 Safari 打开点我就可以直接添加了(给 Shadowrocket)</a></p>
<?php } else { ?>
                                                <p>您好，您目前的 加密方式，混淆，或者协议设置在 Shadowsocks 客户端下无法连接。请您选用 ShadowsocksR 客户端来连接，或者到 资料编辑 页面修改后再来查看此处。</p>
<?php } ?>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>

                        <div class="col-lg-12 col-sm-12">
                            <div class="card">
                                <div class="card-main">
                                    <div class="card-inner margin-bottom-no">
                                        <p class="card-heading">配置二维码</p>


                                        <nav class="tab-nav margin-top-no">
                                            <ul class="nav nav-list">
                                                <li <?php if ($ssr_prefer) { ?>class="active"<?php } ?>>
                                                    <a class="waves-attach" data-toggle="tab" href="#ssr_qrcode"><i class="icon icon-lg">airplanemode_active</i>&nbsp;ShadowsocksR</a>
                                                </li>
                                                <li <?php if (!$ssr_prefer) { ?>class="active"<?php } ?>>
                                                    <a class="waves-attach" data-toggle="tab" href="#ss_qrcode"><i class="icon icon-lg">flight_takeoff</i>&nbsp;Shadowsocks</a>
                                                </li>
                                            </ul>
                                        </nav>
                                        <div class="tab-pane fade <?php if ($ssr_prefer) { ?>active in<?php } ?>" id="ssr_qrcode">
<?php if ($SSR_connectivity) { ?>
                                                <div class="text-center">
                                                    <div id="ss-qr-n"></div>
                                                </div>
<?php } else { ?>
                                                <p>您好，您目前的 加密方式，混淆，或者协议设置在 ShadowsocksR 客户端下无法连接。请您选用 Shadowsocks 客户端来连接，或者到 资料编辑 页面修改后再来查看此处。</p>
<?php } ?>
                                        </div>
                                        <div class="tab-pane fade <?php if (!$ssr_prefer) { ?>active in<?php } ?>" id="ss_qrcode">
<?php if ($SSR_connectivity) { ?>
                                                <nav class="tab-nav margin-top-no">
                                                    <ul class="nav nav-list">
                                                        <li class="active">
                                                            <a class="waves-attach" data-toggle="tab" href="#ss_qrcode_normal"><i class="icon icon-lg">android</i>&nbsp;其他平台</a>
                                                        </li>
                                                        <li>
                                                            <a class="waves-attach" data-toggle="tab" href="#ss_qrcode_win"><i class="icon icon-lg">desktop_windows</i>&nbsp;Windows</a>
                                                        </li>
                                                    </ul>
                                                </nav>
                                                <div class="tab-pane fade active in" id="ss_qrcode_normal">
                                                    <div class="text-center">
                                                        <div id="ss-qr"></div>
                                                    </div>
                                                </div>
                                                <div class="tab-pane fade" id="ss_qrcode_win">
                                                    <div class="text-center">
                                                        <div id="ss-qr-win"></div>
                                                    </div>
                                                </div>
<?php } else { ?>
                                                <p>您好，您目前的 加密方式，混淆，或者协议设置在 Shadowsocks 客户端下无法连接。请您选用 ShadowsocksR 客户端来连接，或者到 资料编辑 页面修改后再来查看此处。</p>
<?php } ?>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>



                    </div>
                </div>
            </section>
        </div>
    </main>







<?php include(TEMPLATE_PATH . 'user/footer.phtml'); ?>


<script src="//cdn.staticfile.org/jquery.qrcode/1.0/jquery.qrcode.min.js"></script>
<script>
<?php if ($SSR_connectivity) { ?>
    var text_qrcode = '{URL::getItemUrl($ss_item, 1)}';
    jQuery('#ss-qr').qrcode({
        "text": text_qrcode
    });

    var text_qrcode_win = '{URL::getItemUrl($ss_item, 2)}';
    jQuery('#ss-qr-win').qrcode({
        "text": text_qrcode_win
    });
<?php } ?>

<?php if ($SSR_connectivity) { ?>
    var text_qrcode2 = '{URL::getItemUrl($ssr_item, 0)}';
    jQuery('#ss-qr-n').qrcode({
        "text": text_qrcode2
    });
<?php } ?>


</script>
