<?php include(TEMPLATE_PATH . 'header.phtml'); ?>

    <main class="content">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-lg-push-4 col-sm-6 col-sm-push-3">
                    <section class="content-inner">

                        <div class="card">
                            <div class="card-main">

                                <div class="card-header">
                                    <div class="card-inner">
                                        <h1 class="card-heading">和我签订契约，成为魔法少女吧。</h1>
                                    </div>
                                </div>

                                <div class="card-inner">

                                    <p class="text-center">
                                        <span class="avatar avatar-inline avatar-lg">
                                            <img alt="Login" src="/theme/material/images/users/avatar-001.jpg">
                                        </span>
                                    </p>

                                    <div class="form-group form-group-label">
                                        <div class="row">
                                            <div class="col-md-10 col-md-push-1">
                                                <label class="floating-label" for="name">昵称</label>
                                                <input class="form-control" id="name" type="text">
                                            </div>
                                        </div>
                                    </div>

                                    <div class="form-group form-group-label">
                                        <div class="row">
                                            <div class="col-md-10 col-md-push-1">
                                                <label class="floating-label" for="email">邮箱</label>
                                                <input class="form-control" id="email" type="text">
                                            </div>
                                        </div>
                                    </div>

<?php if ($_ENV['enable_email_verify']) { ?>
                                    <div class="form-group form-group-label">
                                        <div class="row">
                                            <div class="col-md-10 col-md-push-1">
                                                <label class="floating-label" for="email_code">邮箱验证码</label>
                                                <input class="form-control" id="email_code" type="text">
                                                <button id="email_verify" class="btn btn-block btn-brand-accent waves-attach waves-light">获取验证码</button>
                                            </div>
                                        </div>
                                    </div>
<?php } ?>
                                    <div class="form-group form-group-label">
                                        <div class="row">
                                            <div class="col-md-10 col-md-push-1">
                                                <label class="floating-label" for="passwd">密码</label>
                                                <input class="form-control" id="passwd" type="password">
                                            </div>
                                        </div>
                                    </div>

                                    <div class="form-group form-group-label">
                                        <div class="row">
                                            <div class="col-md-10 col-md-push-1">
                                                <label class="floating-label" for="repasswd">重复密码</label>
                                                <input class="form-control" id="repasswd" type="password">
                                            </div>
                                        </div>
                                    </div>

                                    <div class="form-group form-group-label">
                                        <div class="row">
                                            <div class="col-md-10 col-md-push-1">
                                                <label class="floating-label" for="imtype">选择您的联络方式</label>
                                                <select class="form-control" id="imtype">
                                                    <option></option>
                                                    <option value="1">微信</option>
                                                    <option value="2">QQ</option>
                                                    <option value="3">Google+</option>
                                                    <option value="4">Telegram</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="form-group form-group-label">
                                        <div class="row">
                                            <div class="col-md-10 col-md-push-1">
                                                <label class="floating-label" for="wechat">在这输入联络方式账号</label>
                                                <input class="form-control" id="wechat" type="text">
                                            </div>
                                        </div>
                                    </div>
<?php if ($_ENV['enable_invite_code']) { ?>
                                    <div class="form-group form-group-label">
                                        <div class="row">
                                            <div class="col-md-10 col-md-push-1">
                                                <label class="floating-label" for="code">邀请码</label>
                                                <input class="form-control" id="code" type="text" value="{$code}">
                                            </div>
                                        </div>
                                    </div>
<?php }  if ($geetest_html != null) { ?>
                                    <div class="form-group form-group-label">
                                        <div class="row">
                                            <div class="col-md-10 col-md-push-1">
                                                <div id="embed-captcha"></div>
                                            </div>
                                        </div>
                                    </div>
<?php }
if ($recaptcha_sitekey != null) { ?>
                                    <div class="form-group">
                                        <div class="row">
                                            <div align="center" class="g-recaptcha" data-sitekey="<?= $recaptcha_sitekey ?>"></div>
                                        </div>
                                    </div>
<?php } ?>

                                    <div class="form-group">
                                        <div class="row">
                                            <div class="col-md-10 col-md-push-1">
                                                <button id="tos" type="submit" class="btn btn-block btn-brand waves-attach waves-light">注册</button>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <div class="row">
                                            <div class="col-md-10 col-md-push-1">
                                                <p>注册即代表同意<a href="/tos">服务条款</a>，以及保证所录入信息的真实性，如有不实信息会导致账号被删除。</p>
                                            </div>
                                        </div>
                                    </div>

                                </div>

                            </div>
                        </div>
                        <div class="clearfix">
                            <p class="margin-no-top pull-left"><a class="btn btn-flat btn-brand waves-attach" href="/auth/login">已经注册？请登录</a></p>
                        </div>

<?php include(TEMPLATE_PATH . 'dialog.phtml'); ?>

                        <div aria-hidden="true" class="modal modal-va-middle fade" id="tos_modal" role="dialog" tabindex="-1">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-heading">
                                        <h2 class="modal-title">注册 TOS</h2>
                                    </div>
                                    <div class="modal-inner">

<?php include(TEMPLATE_PATH . 'reg_tos.phtml'); ?>

                                    </div>
                                    <div class="modal-footer">
                                        <p class="text-right"><button class="btn btn-flat btn-brand-accent waves-attach waves-effect" data-dismiss="modal" type="button" id="cancel">不同意</button><button class="btn btn-flat btn-brand-accent waves-attach waves-effect" data-dismiss="modal" id="reg" type="button">同意</button></p>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </section>
                </div>
            </div>
        </div>
    </main>

<?php include(TEMPLATE_PATH . 'footer.phtml'); ?>

<script>
    $(document).ready(function(){
        function register(){

            document.getElementById("tos").disabled = true;

            $.ajax({
                type:"POST",
                url:"/auth/register",
                dataType:"json",
                data:{
                    email: $("#email").val(),
                    name: $("#name").val(),
                    passwd: $("#passwd").val(),
                    repasswd: $("#repasswd").val(),
                    wechat: $("#wechat").val(),<?php if ($recaptcha_sitekey != null) { ?>
                    recaptcha: grecaptcha.getResponse(),<?php } ?>
                    imtype: $("#imtype").val()<?php if ($_ENV['enable_invite_code']) { ?>,
                    code: $("#code").val()<?php } if ($_ENV['enable_email_verify']) { ?>,
                    emailcode: $("#email_code").val()<?php } if ($geetest_html != null) { ?>,
                    geetest_challenge: validate.geetest_challenge,
                    geetest_validate: validate.geetest_validate,
                    geetest_seccode: validate.geetest_seccode<?php } ?>
                },
                success:function(data){
                    if(data.ret == 1){
                        $("#result").modal();
                        $("#msg").html(data.msg);
                        window.setTimeout("location.href='/auth/login'", <?= $_ENV['jump_delay'] ?>);
                    }else{
                        $("#result").modal();
                        $("#msg").html(data.msg);
                        document.getElementById("tos").disabled = false;
<?php if ($geetest_html != null) { ?>
                        captcha.refresh();
<?php } ?>
                    }
                },
                error:function(jqXHR){
            $("#msg-error").hide(10);
            $("#msg-error").show(100);
            $("#msg-error-p").html("发生错误："+jqXHR.status);
            document.getElementById("tos").disabled = false;
<?php if ($geetest_html != null) { ?>
            captcha.refresh();
<?php } ?>
                }
            });
        }
        $("html").keydown(function(event){
            if(event.keyCode==13){
                $("#tos_modal").modal();
            }
        });

<?php if ($geetest_html != null) { ?>
        $('div.modal').on('shown.bs.modal', function() {
            $("div.gt_slider_knob").hide();
        });
        $('div.modal').on('hidden.bs.modal', function() {
            $("div.gt_slider_knob").show();
        });
<?php } ?>

        $("#reg").click(function(){
            register();
        });

        $("#tos").click(function(){
<?php if ($geetest_html != null) { ?>
            if(typeof validate == 'undefined')
            {
                $("#result").modal();
                $("#msg").html("请滑动验证码来完成验证。");
                return;
            }
            if (!validate) {
                $("#result").modal();
                $("#msg").html("请滑动验证码来完成验证。");
                return;
            }
<?php } ?>
            $("#tos_modal").modal();
        });
    })
</script>


<?php if ($_ENV['enable_email_verify']) { ?>
<script>
    var wait=60;
    function time(o) {
        if (wait == 0) {
            o.removeAttr("disabled");
            o.text("获取验证码");
            wait = 60;
        } else {
            o.attr("disabled","disabled");
            o.text("重新发送(" + wait + ")");
            wait--;
            setTimeout(function() {
                time(o)
            },
            1000)
        }
    }

    $(document).ready(function () {
        $("#email_verify").click(function () {
            time($("#email_verify"));
            $.ajax({
                type: "POST",
                url: "send",
                dataType: "json",
                data: {
                    email: $("#email").val()
                },
                success: function (data) {
                    if (data.ret) {
                        $("#result").modal();
                        $("#msg").html(data.msg);
                    } else {
                        $("#result").modal();
                        $("#msg").html(data.msg);
                    }
                },
                error: function (jqXHR) {
                    $("#result").modal();
                    $("#msg").html(data.msg+"     出现了一些错误。");
                }
            })
        })
    })
</script>
<?php } ?>

<?php if ($geetest_html != null) { ?>
<script>
    var handlerEmbed = function (captchaObj) {
        // 将验证码加到id为captcha的元素里

        captchaObj.onSuccess(function () {
            validate = captchaObj.getValidate();
        });

        captchaObj.appendTo("#embed-captcha");

        captcha = captchaObj;
        // 更多接口参考：http://www.geetest.com/install/sections/idx-client-sdk.html
    };

    initGeetest({
        gt: "<?= $geetest_html->gt ?>",
        challenge: "<?= $geetest_html->challenge ?>",
        product: "embed", // 产品形式，包括：float，embed，popup。注意只对PC版验证码有效
        offline: <?php if ($geetest_html->success) { ?>0<?php } else { ?>1<?php } ?> // 表示用户后台检测极验服务器是否宕机，与SDK配合，用户一般不需要关注
    }, handlerEmbed);
</script>

<?php } ?>
<?php if ($recaptcha_sitekey != null) { ?><script src="https://recaptcha.net/recaptcha/api.js" async defer></script><?php } ?>
