<?php include(TEMPLATE_PATH . 'admin/main.phtml'); ?>

<main class="content">
    <div class="content-header ui-content-header">
        <div class="container">
            <h1 class="content-heading">工单</h1>
        </div>
    </div>
    <div class="container">
        <div class="col-lg-12 col-sm-12">
            <section class="content-inner margin-top-no">

                <div class="card">
                    <div class="card-main">
                        <div class="card-inner">
                            <p>系统中的工单</p>
                            <p>显示表项:
                              <?php include(TEMPLATE_PATH . 'table/checkbox.phtml'); ?>
                            </p>
                        </div>
                    </div>
                </div>

                <div class="table-responsive">
                    <?php include(TEMPLATE_PATH . 'table/table.phtml'); ?>
                </div>

            </section>
        </div>
    </div>

</main>

<?php include(TEMPLATE_PATH . 'admin/footer.phtml'); ?>

<script>
<?php include(TEMPLATE_PATH . 'table/js_1.phtml'); ?>
$(document).ready(function(){
  table = $('#table_tickets').DataTable({
        ajax: 'ticket/ajax',
        processing: true,
        serverSide: true,
        order: [[ 1, 'desc' ]]
    })

    <?php include(TEMPLATE_PATH . 'table/js_2.phtml'); ?>
});
</script>
