<table id="table_1" class="mdl-data-table" cellspacing="0" width="100%">
    <thead>
        <tr>
<?php foreach ($table_config['total_column'] as $key => $value) { ?>
            <th class="<?= $key; ?>"><?= $value; ?></th>
<?php } ?>
        </tr>
    </thead>
    <tfoot>
        <tr>
<?php foreach ($table_config['total_column'] as $key => $value) { ?>
            <th class="<?= $key; ?>"><?= $value; ?></th>
<?php } ?>
        </tr>
    </tfoot>
    <tbody>
    </tbody>
</table>
