<?php include(TEMPLATE_PATH . 'admin/main.phtml'); ?>

<main class="content">
    <div class="content-header ui-content-header">
        <div class="container">
            <h1 class="content-heading">购买记录</h1>
        </div>
    </div>
    <div class="container">
        <div class="col-lg-12 col-sm-12">
            <section class="content-inner margin-top-no">

                <div class="card">
                    <div class="card-main">
                        <div class="card-inner">
                            <p>系统中所有购买记录。</p>
                            <p>显示表项:
                                <?= include(TEMPLATE_PATH . 'table/checkbox.phtml'); ?>
                            </p>
                        </div>
                    </div>
                </div>

                <div class="table-responsive">
                    <?php include(TEMPLATE_PATH . 'table/table.phtml'); ?>
                </div>


                <div aria-hidden="true" class="modal modal-va-middle fade" id="delete_modal" role="dialog" tabindex="-1">
                    <div class="modal-dialog modal-xs">
                        <div class="modal-content">
                            <div class="modal-heading">
                                <a class="modal-close" data-dismiss="modal">×</a>
                                <h2 class="modal-title">确认要退订？</h2>
                            </div>
                            <div class="modal-inner">
                                <p>请您确认。</p>
                            </div>
                            <div class="modal-footer">
                                <p class="text-right"><button class="btn btn-flat btn-brand-accent waves-attach waves-effect" data-dismiss="modal" type="button">取消</button><button class="btn btn-flat btn-brand-accent waves-attach" data-dismiss="modal" id="delete_input" type="button">确定</button></p>
                            </div>
                        </div>
                    </div>
                </div>

<?php include(TEMPLATE_PATH . 'dialog.phtml'); ?>

        </div>

    </div>
</main>

<?php include(TEMPLATE_PATH . 'admin/footer.phtml'); ?>

<script>
function delete_modal_show(id) {
    deleteid=id;
    $("#delete_modal").modal();
}

<?php include(TEMPLATE_PATH . 'table/js_1.phtml'); ?>

$(document).ready(function(){
<?php include(TEMPLATE_PATH . 'table/js_2.phtml'); ?>

    function delete_id(){
        $.ajax({
            type:"DELETE",
            url:"/admin/bought",
            dataType:"json",
            data:{
                id: deleteid
            },
            success:function(data){
                if(data.ret){
                    $("#result").modal();
                    $("#msg").html(data.msg);
                    $("#row_delete_"+deleteid).attr("disabled","true");
                }else{
                    $("#result").modal();
                    $("#msg").html(data.msg);
                }
            },
            error:function(jqXHR){
                $("#result").modal();
                $("#msg").html(data.msg+"  发生错误了。");
            }
        });
    }
    $("#delete_input").click(function(){
        delete_id();
    });
})

</script>
